# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'system_select_coordinate_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SystemSelectCoordinateDialogBase(object):
    def setupUi(self, SystemSelectCoordinateDialogBase):
        SystemSelectCoordinateDialogBase.setObjectName("SystemSelectCoordinateDialogBase")
        SystemSelectCoordinateDialogBase.resize(450, 400)
        SystemSelectCoordinateDialogBase.setMinimumSize(QtCore.QSize(450, 400))
        SystemSelectCoordinateDialogBase.setMaximumSize(QtCore.QSize(450, 400))
        self.button_box = QtWidgets.QDialogButtonBox(SystemSelectCoordinateDialogBase)
        self.button_box.setGeometry(QtCore.QRect(190, 360, 81, 23))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.button_box.setObjectName("button_box")
        self.setCrsForProjectButton = QtWidgets.QPushButton(SystemSelectCoordinateDialogBase)
        self.setCrsForProjectButton.setGeometry(QtCore.QRect(70, 320, 321, 23))
        self.setCrsForProjectButton.setObjectName("setCrsForProjectButton")
        self.setCrsForLayersButton = QtWidgets.QPushButton(SystemSelectCoordinateDialogBase)
        self.setCrsForLayersButton.setGeometry(QtCore.QRect(70, 280, 321, 23))
        self.setCrsForLayersButton.setObjectName("setCrsForLayersButton")
        self.listWidget = QtWidgets.QListWidget(SystemSelectCoordinateDialogBase)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 420, 250))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(SystemSelectCoordinateDialogBase)
        self.button_box.accepted.connect(SystemSelectCoordinateDialogBase.accept) # type: ignore
        self.button_box.rejected.connect(SystemSelectCoordinateDialogBase.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SystemSelectCoordinateDialogBase)

    def retranslateUi(self, SystemSelectCoordinateDialogBase):
        _translate = QtCore.QCoreApplication.translate
        SystemSelectCoordinateDialogBase.setWindowTitle(_translate("SystemSelectCoordinateDialogBase", "SystemSelectCoordinate"))
        self.setCrsForProjectButton.setText(_translate("SystemSelectCoordinateDialogBase", "Установить систему координат для открытого проекта"))
        self.setCrsForLayersButton.setText(_translate("SystemSelectCoordinateDialogBase", "Установить систему координат для выбранных слоёв"))
